baseURL = 'https://rmkraus.github.io/doc-test-hugo'
languageCode = 'en-us'
title = 'My New Hugo Site'
enableRobotsTXT = true

[params]
  [params.robots]
    llmsTXT = true

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
